name: Build & Deploy API

on:
  push:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Run FastAPI
        working-directory: src
        run: uvicorn main:app --host 0.0.0.0 --port 8000
